/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.profree.desktop.Views;

import com.formdev.flatlaf.FlatClientProperties;
import java.beans.PropertyVetoException;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author Hanif
 */
public class Dashboard extends javax.swing.JInternalFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
        
        ProgramerTerbaik.putClientProperty( FlatClientProperties.STYLE, "selectedBackground:#FDFFFC" );
        Riwayat.putClientProperty( FlatClientProperties.STYLE, "selectedBackground:#FDFFFC" );
        Kantor.putClientProperty( FlatClientProperties.STYLE, "selectedBackground:#FDFFFC" );
        Kemampuan.putClientProperty( FlatClientProperties.STYLE, "selectedBackground:#FDFFFC" );
        LamanLabuh.putClientProperty( FlatClientProperties.STYLE, "selectedBackground:#FDFFFC" );
        DataDiri.putClientProperty( FlatClientProperties.STYLE, "selectedBackground:#FDFFFC" );
        
        Menu.add(ProgramerTerbaik);
        Menu.add(Riwayat);
        Menu.add(Kantor);
        Menu.add(Kemampuan);
        Menu.add(LamanLabuh);
        Menu.add(DataDiri);
        
        try {
            this.setMaximum(true);
            BasicInternalFrameUI bi = (BasicInternalFrameUI)this.getUI();
            bi.setNorthPane(null);
        } catch (PropertyVetoException e) {}
        
        ProgramerTerbaik programerTerbaik = new ProgramerTerbaik();
        programerTerbaik.setVisible(true);
        Halaman.add(programerTerbaik);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Menu = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        ProgramerTerbaik = new javax.swing.JToggleButton();
        Riwayat = new javax.swing.JToggleButton();
        Kantor = new javax.swing.JToggleButton();
        Kemampuan = new javax.swing.JToggleButton();
        LamanLabuh = new javax.swing.JToggleButton();
        DataDiri = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Halaman = new javax.swing.JDesktopPane();

        setBorder(null);

        jPanel1.setBackground(new java.awt.Color(253, 255, 252));

        jPanel2.setBackground(new java.awt.Color(0, 102, 255));

        ProgramerTerbaik.setBackground(new java.awt.Color(0, 102, 255));
        ProgramerTerbaik.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        ProgramerTerbaik.setForeground(new java.awt.Color(255, 255, 255));
        ProgramerTerbaik.setSelected(true);
        ProgramerTerbaik.setText("Programer Terbaik");
        ProgramerTerbaik.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        ProgramerTerbaik.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ProgramerTerbaik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProgramerTerbaikActionPerformed(evt);
            }
        });

        Riwayat.setBackground(new java.awt.Color(0, 102, 255));
        Riwayat.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        Riwayat.setForeground(new java.awt.Color(255, 255, 255));
        Riwayat.setText("RIwayat");
        Riwayat.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        Riwayat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Riwayat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RiwayatActionPerformed(evt);
            }
        });

        Kantor.setBackground(new java.awt.Color(0, 102, 255));
        Kantor.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        Kantor.setForeground(new java.awt.Color(255, 255, 255));
        Kantor.setText("Kantor");
        Kantor.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        Kantor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Kantor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KantorActionPerformed(evt);
            }
        });

        Kemampuan.setBackground(new java.awt.Color(0, 102, 255));
        Kemampuan.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        Kemampuan.setForeground(new java.awt.Color(255, 255, 255));
        Kemampuan.setText("Kemampuan");
        Kemampuan.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        Kemampuan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Kemampuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KemampuanActionPerformed(evt);
            }
        });

        LamanLabuh.setBackground(new java.awt.Color(0, 102, 255));
        LamanLabuh.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        LamanLabuh.setForeground(new java.awt.Color(255, 255, 255));
        LamanLabuh.setText("Laman Labuh");
        LamanLabuh.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        LamanLabuh.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        LamanLabuh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LamanLabuhActionPerformed(evt);
            }
        });

        DataDiri.setBackground(new java.awt.Color(0, 102, 255));
        DataDiri.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        DataDiri.setForeground(new java.awt.Color(255, 255, 255));
        DataDiri.setText("Data Diri");
        DataDiri.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        DataDiri.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        DataDiri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DataDiriActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(253, 255, 252));
        jLabel1.setFont(new java.awt.Font("Poppins", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(253, 255, 252));
        jLabel1.setText("Profree");

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Keluar");
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ProgramerTerbaik, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                            .addComponent(Riwayat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Kantor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Kemampuan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LamanLabuh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DataDiri, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(ProgramerTerbaik)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Riwayat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Kantor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Kemampuan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LamanLabuh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DataDiri)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Halaman.setBackground(new java.awt.Color(253, 255, 252));

        javax.swing.GroupLayout HalamanLayout = new javax.swing.GroupLayout(Halaman);
        Halaman.setLayout(HalamanLayout);
        HalamanLayout.setHorizontalGroup(
            HalamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 524, Short.MAX_VALUE)
        );
        HalamanLayout.setVerticalGroup(
            HalamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 476, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Halaman))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Halaman)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void KantorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KantorActionPerformed
        // TODO add your handling code here:
        Halaman.removeAll();
        Kantor kantor = new Kantor();
        kantor.setVisible(true);
        Halaman.add(kantor);
    }//GEN-LAST:event_KantorActionPerformed

    private void KemampuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KemampuanActionPerformed
        // TODO add your handling code here:
        Halaman.removeAll();
        Kemampuan kemampuan = new Kemampuan();
        kemampuan.setVisible(true);
        Halaman.add(kemampuan);
    }//GEN-LAST:event_KemampuanActionPerformed

    private void LamanLabuhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LamanLabuhActionPerformed
        // TODO add your handling code here:
        Halaman.removeAll();
        LamanLabuh lamanLabuh = new LamanLabuh();
        lamanLabuh.setVisible(true);
        Halaman.add(lamanLabuh);
    }//GEN-LAST:event_LamanLabuhActionPerformed

    private void DataDiriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DataDiriActionPerformed
        // TODO add your handling code here:
        Halaman.removeAll();
        DataDiri dataDiri = new DataDiri();
        dataDiri.setVisible(true);
        Halaman.add(dataDiri);
    }//GEN-LAST:event_DataDiriActionPerformed

    private void RiwayatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RiwayatActionPerformed
        // TODO add your handling code here:
        Halaman.removeAll();
        Riwayat riwayat = new Riwayat();
        riwayat.setVisible(true);
        Halaman.add(riwayat);
    }//GEN-LAST:event_RiwayatActionPerformed

    private void ProgramerTerbaikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProgramerTerbaikActionPerformed
        // TODO add your handling code here:
        Halaman.removeAll();
        ProgramerTerbaik programerTerbaik = new ProgramerTerbaik();
        programerTerbaik.setVisible(true);
        Halaman.add(programerTerbaik);
    }//GEN-LAST:event_ProgramerTerbaikActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton DataDiri;
    private javax.swing.JDesktopPane Halaman;
    private javax.swing.JToggleButton Kantor;
    private javax.swing.JToggleButton Kemampuan;
    private javax.swing.JToggleButton LamanLabuh;
    private javax.swing.ButtonGroup Menu;
    private javax.swing.JToggleButton ProgramerTerbaik;
    private javax.swing.JToggleButton Riwayat;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
