/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.profree.desktop.Views;

import com.profree.desktop.Controllers.DataAkun;

/**
 *
 * @author Hanif
 */
public class KartuOrang extends javax.swing.JPanel {
    final private int id;
    final private String programer;

    /**
     * Creates new form KartuOrang
     */
    public KartuOrang(int id, String nama) {
        initComponents();
        this.id = id;
        this.programer = nama;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nama = new javax.swing.JLabel();
        pengalaman = new javax.swing.JLabel();
        projek = new javax.swing.JLabel();

        setBackground(new java.awt.Color(253, 255, 252));
        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 255), 3, true));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        nama.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        nama.setForeground(new java.awt.Color(0, 102, 255));
        nama.setText("Nama Freelancer");
        nama.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        pengalaman.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        pengalaman.setText("Pengalaman");

        projek.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        projek.setText("Total Projek");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(projek)
                    .addComponent(pengalaman)
                    .addComponent(nama))
                .addContainerGap(268, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(nama)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pengalaman)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(projek)
                .addContainerGap(12, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        String deskripsi = DataAkun.getDeskripsi(id);
        Freelancer popup = new Freelancer(null, true, deskripsi, programer);
        popup.setVisible(true);
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel nama;
    public javax.swing.JLabel pengalaman;
    public javax.swing.JLabel projek;
    // End of variables declaration//GEN-END:variables
}
