/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.profree.desktop.Views;

import com.profree.desktop.Controllers.DataPilihan;
import com.profree.desktop.Controllers.SPK;
import com.profree.desktop.Models.Alternatif;
import java.awt.Color;
import java.beans.PropertyVetoException;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JPanel;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author Hanif
 */
public class ProgramerTerbaik extends javax.swing.JInternalFrame {

    /**
     * Creates new form Kantor
     */
    public ProgramerTerbaik() {
        initComponents();
        try {
            this.setMaximum(true);
            BasicInternalFrameUI bi = (BasicInternalFrameUI)this.getUI();
            bi.setNorthPane(null);
        } catch (PropertyVetoException e) {}
        
         ArrayList<String> produk = DataPilihan.getDaftar("jenis_produk");
        ArrayList<String> bahasa = DataPilihan.getDaftar("bahasa_pemograman");
        
        for (String nama : produk) {
            jproduk.addItem(nama);
        }
        
        for (String nama : bahasa) {
            jbahasa.addItem(nama);
        }
        
        jproduk.setSelectedIndex(-1);
        jbahasa.setSelectedIndex(-1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JenisKelamin = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jbahasa = new javax.swing.JComboBox<>();
        jproduk = new javax.swing.JComboBox<>();
        cari = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        hasil_pencarian = new javax.swing.JScrollPane();

        setBackground(new java.awt.Color(0, 102, 255));
        setBorder(null);

        jPanel1.setBackground(new java.awt.Color(253, 255, 252));

        jLabel2.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jLabel2.setText("Cari Programer Terbaik");

        jLabel3.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel3.setText("Produk");

        jLabel4.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel4.setText("Bahasa");

        jbahasa.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N

        jproduk.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N

        cari.setBackground(new java.awt.Color(0, 102, 255));
        cari.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        cari.setForeground(new java.awt.Color(255, 255, 255));
        cari.setText("Cari");
        cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jLabel5.setText("Hasil");

        hasil_pencarian.setBackground(new java.awt.Color(253, 255, 252));
        hasil_pencarian.setBorder(null);
        hasil_pencarian.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jproduk, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbahasa, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cari))
                    .addComponent(hasil_pencarian))
                .addGap(17, 17, 17))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jproduk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jbahasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cari))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(hasil_pencarian, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariActionPerformed
        // TODO add your handling code here:
        JPanel daftar_alternatif = new JPanel();
        daftar_alternatif.setBackground(new Color(253, 255, 252));
        daftar_alternatif.setLayout(new BoxLayout(daftar_alternatif, BoxLayout.Y_AXIS));
        daftar_alternatif.setBorder(BorderFactory.createEmptyBorder(5, 5, 5, 10));
        daftar_alternatif.removeAll();
        
        ArrayList<Alternatif> daftar_orang = SPK.CariTerbaik(jproduk.getSelectedIndex()+1, jbahasa.getSelectedIndex()+1);
        
        for (Alternatif orang : daftar_orang){
            KartuOrang alternatif = new KartuOrang();
            alternatif.nama.setText(orang.getNama());
            alternatif.pengalaman.setText("Pengalaman " + (int)orang.getPengalaman() + " Tahun");
            alternatif.projek.setText((int)orang.getProjek() + " Projek telah dikerjakan");
            alternatif.setVisible(true);
            daftar_alternatif.add(alternatif);
            daftar_alternatif.add(Box.createVerticalStrut(10));
        }
        
        daftar_alternatif.setVisible(true);
        hasil_pencarian.setViewportView(daftar_alternatif);
    }//GEN-LAST:event_cariActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup JenisKelamin;
    private javax.swing.JButton cari;
    private javax.swing.JScrollPane hasil_pencarian;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> jbahasa;
    private javax.swing.JComboBox<String> jproduk;
    // End of variables declaration//GEN-END:variables
}
